name: 'Project Wiki Edit Discord Notifications'
description: 'GitHub Action to notify a Discord channel when someone edits the project wiki.'
branding:
  icon: message-circle
  color: purple
inputs:
  discord-webhook-url:  # id of input
    description: 'The Discord channel webhook url'
    required: true
  ignore-collaborators:
    description: 'If set to true, changes made by repo/org collaborators will not trigger the webhook'
    default: false
  token:
    description: 'GITHUB_TOKEN or a repo scoped PAT'
    default: ${{ github.token }}
  discord-username:
    description: 'Discord display username'
    default: 'github-actions'
  discord-avatar-url:
    description: 'Discord avatar url'
    default: 'https://avatars.githubusercontent.com/in/15368'
runs:
  using: 'node16'
  main: 'dist/index.js'